"""initial

Revision ID: 504810a90944
Revises: 
Create Date: 2025-02-14 11:09:10.385605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504810a90944'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('wb_token', sa.String(), nullable=True),
    sa.Column('stable_expence', sa.Integer(), server_default='0', nullable=False),
    sa.Column('variable_expence', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('Europe/Moscow', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('Europe/Moscow', now())"), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('user_moving',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('Europe/Moscow', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_variable_expence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('expence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('Europe/Moscow', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_variable_expence')
    op.drop_table('user_moving')
    op.drop_table('user')
    # ### end Alembic commands ###
